#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

ruby_with_nodejs_context "bundle exec rake players:rerank RAILS_ENV=${RAILS_ENV:-production}"