development:
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

test: &test
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

production:
  pool: 50
  timeout: 5000
  encoding: utf8
  adapter: postgresql
  database: webapp
  username: webapp
  password: Password1
  host:     localhost
  port:     5432

